[profile.default]
src = "src"
out = "out"
libs = ["lib"]

solc_version = "0.8.16"

[rpc_endpoints]
bsc-testnet= "${BSCTEST_RPC_URL}"
goerli = "${GOERLI_RPC_URL}"


[etherscan]
bsc-testnet = { key = "${BSCSCAN_API_KEY}", url = "https://api-testnet.bscscan.com/api" }
goerli = { key = "${ETHERSCAN_API_KEY}" }

# See more config options https://github.com/foundry-rs/foundry/blob/master/crates/config/README.md#all-options
